# Generated by Django 5.2.9 on 2026-01-03 15:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Access Code",
                "verbose_name_plural": "Access Codes",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tên danh mục")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name hoặc emoji",
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Danh mục",
                "verbose_name_plural": "Danh mục",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tên ví")),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Số dư"
                    ),
                ),
                (
                    "wallet_type",
                    models.CharField(
                        choices=[
                            ("cash", "Tiền mặt"),
                            ("bank", "Ngân hàng"),
                            ("credit_card", "Thẻ tín dụng"),
                            ("e_wallet", "Ví điện tử"),
                        ],
                        default="cash",
                        max_length=50,
                        verbose_name="Loại ví",
                    ),
                ),
                (
                    "exclude_from_total",
                    models.BooleanField(
                        default=False,
                        help_text="Ví tiết kiệm không tính vào dòng tiền chi tiêu hàng ngày",
                        verbose_name="Không tính vào tổng",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ví",
                "verbose_name_plural": "Ví",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Số tiền"
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("weekly", "Hàng tuần"), ("monthly", "Hàng tháng")],
                        default="monthly",
                        max_length=20,
                        verbose_name="Chu kỳ",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Ngày bắt đầu")),
                ("end_date", models.DateField(verbose_name="Ngày kết thúc")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.category",
                        verbose_name="Danh mục",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ngân sách",
                "verbose_name_plural": "Ngân sách",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecurringTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Tên giao dịch"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Số tiền"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Hàng ngày"),
                            ("weekly", "Hàng tuần"),
                            ("monthly", "Hàng tháng"),
                            ("yearly", "Hàng năm"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="Tần suất",
                    ),
                ),
                ("next_run_date", models.DateField(verbose_name="Ngày chạy tiếp theo")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("expense", "Chi tiêu"), ("income", "Thu nhập")],
                        default="expense",
                        max_length=20,
                        verbose_name="Loại giao dịch",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.category",
                        verbose_name="Danh mục",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.wallet",
                        verbose_name="Ví",
                    ),
                ),
            ],
            options={
                "verbose_name": "Giao dịch định kỳ",
                "verbose_name_plural": "Giao dịch định kỳ",
                "ordering": ["next_run_date"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Số tiền"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Text gốc: 'Ăn phở 50k'",
                        verbose_name="Mô tả",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("expense", "Chi tiêu"),
                            ("income", "Thu nhập"),
                            ("debt_loan", "Cho vay"),
                            ("debt_borrow", "Đi vay"),
                            ("debt_collect", "Thu nợ"),
                            ("debt_repay", "Trả nợ"),
                        ],
                        default="expense",
                        max_length=20,
                        verbose_name="Loại giao dịch",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        help_text="Tên người vay/nợ",
                        max_length=100,
                        null=True,
                        verbose_name="Người liên quan",
                    ),
                ),
                (
                    "raw_ocr_text",
                    models.TextField(
                        blank=True,
                        help_text="Text full từ hóa đơn",
                        null=True,
                        verbose_name="Text từ OCR",
                    ),
                ),
                (
                    "qdrant_point_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID mapping sang Qdrant",
                        null=True,
                        verbose_name="Qdrant Point ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Ngày giao dịch"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.category",
                        verbose_name="Danh mục",
                    ),
                ),
                (
                    "recurring_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.recurringtransaction",
                        verbose_name="Giao dịch định kỳ",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.wallet",
                        verbose_name="Ví",
                    ),
                ),
            ],
            options={
                "verbose_name": "Giao dịch",
                "verbose_name_plural": "Giao dịch",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(fields=["-date"], name="app_transac_date_3a8a98_idx"),
                    models.Index(
                        fields=["category", "date"],
                        name="app_transac_categor_bb5603_idx",
                    ),
                    models.Index(
                        fields=["transaction_type", "date"],
                        name="app_transac_transac_9a3c22_idx",
                    ),
                ],
            },
        ),
    ]
